import { StyleSheet } from 'react-native';

import type { AppColors } from '../../../shared/theme/colors';

export function createStyles(colors: AppColors, isTablet: boolean) {
  return StyleSheet.create({
    actionRow: {
      flexDirection: isTablet ? 'row' : 'column',
      gap: 12,
      width: isTablet ? 'auto' : '100%',
    },
    secondaryAction: {
      minHeight: 52,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
      flexDirection: 'row',
      gap: 10,
    },
    secondaryActionText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    primaryAction: {
      minHeight: 52,
      borderRadius: 18,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 20,
      flexDirection: 'row',
      gap: 10,
    },
    primaryActionText: {
      color: colors.onPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
    },
    dangerActionRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    dangerOutlineAction: {
      minHeight: 44,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.dangerAction,
      backgroundColor: colors.dangerBackground,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dangerActionDisabled: {
      opacity: 0.7,
    },
    dangerOutlineActionText: {
      color: colors.dangerAction,
      fontSize: 13,
      fontWeight: '800',
    },
    activityCard: {
      gap: 20,
    },
    activityHeader: {
      flexDirection: isTablet ? 'row' : 'column',
      alignItems: isTablet ? 'flex-start' : 'stretch',
      justifyContent: 'space-between',
      gap: 14,
    },
    cardHeading: {
      gap: 6,
      flex: 1,
    },
    cardTitle: {
      color: colors.text,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '800',
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    filterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    filterChip: {
      minHeight: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    filterChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
    },
    filterChipDisabled: {
      opacity: 0.6,
    },
    filterChipText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    filterPanel: {
      gap: 12,
      padding: 16,
      borderRadius: 18,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterPanelTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    filterOptionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    filterOption: {
      minHeight: 38,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterOptionActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    filterOptionText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    filterOptionTextActive: {
      color: colors.onPrimary,
    },
    chartScroll: {
      marginHorizontal: -4,
    },
    chartContent: {
      paddingHorizontal: 4,
    },
    chartFrame: {
      minWidth: isTablet ? undefined : 760,
      gap: 12,
    },
    chart: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
      height: 220,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    chartColumnWrap: {
      width: 24,
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 6,
    },
    chartValue: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '700',
    },
    chartColumn: {
      width: 12,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      backgroundColor: colors.primary,
    },
    chartColumnEmpty: {
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    chartColumnHighlighted: {
      backgroundColor: colors.secondary,
    },
    chartLabel: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '700',
    },
    activitySummaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    activitySummaryCard: {
      minWidth: isTablet ? 120 : 106,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 4,
    },
    activitySummaryCardSelected: {
      backgroundColor: colors.secondaryContainer,
      borderColor: colors.secondary,
    },
    activitySummaryDay: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    activitySummaryDaySelected: {
      color: colors.onSecondaryContainer,
    },
    activitySummaryValue: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
    },
    activitySummaryValueSelected: {
      color: colors.onSecondaryContainer,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 48 : 20,
      paddingVertical: 24,
      backgroundColor: colors.overlay,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    modalCard: {
      alignSelf: 'center',
      width: '100%',
      maxWidth: isTablet ? 620 : 460,
      maxHeight: '80%',
      borderRadius: 28,
      padding: 24,
      backgroundColor: colors.surface,
      gap: 18,
    },
    modalHeader: {
      flexDirection: isTablet ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: isTablet ? 'flex-start' : 'stretch',
      gap: 12,
    },
    modalHeading: {
      flex: 1,
      gap: 6,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '800',
    },
    modalSubtitle: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 20,
    },
    modalCloseButton: {
      minHeight: 40,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalCloseButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    modalState: {
      minHeight: 120,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 20,
      gap: 12,
    },
    modalStateText: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      fontWeight: '600',
    },
    modalList: {
      flexGrow: 0,
    },
    modalListContent: {
      gap: 12,
      paddingBottom: 4,
    },
    respondentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    respondentIndexWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    respondentIndex: {
      color: colors.onPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    respondentContent: {
      flex: 1,
      gap: 4,
    },
    respondentPrimary: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    respondentSecondary: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    tableCard: {
      gap: 0,
      padding: 0,
      overflow: 'hidden',
    },
    tableHeader: {
      paddingHorizontal: 24,
      paddingTop: 22,
      paddingBottom: 18,
      flexDirection: isTablet ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: isTablet ? 'center' : 'flex-start',
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    tableColumns: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 14,
      backgroundColor: colors.surfaceMuted,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tableColumnLabel: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    tableQuestionColumn: {
      flex: isTablet ? 1.05 : 1,
      paddingRight: 18,
    },
    tableAnswerColumn: {
      flex: isTablet ? 1.6 : 1,
    },
    tableRow: {
      flexDirection: isTablet ? 'row' : 'column',
      gap: 16,
      paddingHorizontal: 24,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    tableQuestion: {
      color: colors.text,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    tableMeta: {
      color: colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 6,
      fontWeight: '600',
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    chip: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surface,
    },
    chipStrong: {
      backgroundColor: colors.secondaryContainer,
    },
    chipText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    chipStrongText: {
      color: colors.onSecondaryContainer,
    },
    tableFooter: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 24,
      paddingVertical: 16,
      backgroundColor: colors.surfaceMuted,
    },
    tableFooterButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 36,
    },
    tableFooterText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '700',
    },
  });
}
