import { StyleSheet } from 'react-native';

import type { AppColors } from '../../../shared/theme/colors';

export function createStyles(colors: AppColors, isTablet: boolean) {
  return StyleSheet.create({
    actionRow: {
      flexDirection: isTablet ? 'row' : 'column',
      gap: 12,
      width: isTablet ? 'auto' : '100%',
    },
    secondaryAction: {
      minHeight: 52,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
      flexDirection: 'row',
      gap: 10,
    },
    secondaryActionText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    primaryAction: {
      minHeight: 52,
      borderRadius: 18,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 20,
      flexDirection: 'row',
      gap: 10,
    },
    primaryActionText: {
      color: colors.onPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
    },
    dangerActionRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    dangerOutlineAction: {
      minHeight: 44,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.dangerAction,
      backgroundColor: colors.dangerBackground,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dangerActionDisabled: {
      opacity: 0.7,
    },
    dangerOutlineActionText: {
      color: colors.dangerAction,
      fontSize: 13,
      fontWeight: '800',
    },
    activityCard: {
      width: '100%',
      maxWidth: isTablet ? 980 : undefined,
      alignSelf: 'center',
      gap: 16,
      padding: isTablet ? 20 : 22,
      overflow: 'visible',
    },
    activityHeader: {
      flexDirection: isTablet ? 'row' : 'column',
      alignItems: isTablet ? 'flex-start' : 'stretch',
      justifyContent: 'space-between',
      gap: 12,
      zIndex: 20,
    },
    cardHeading: {
      gap: 4,
      flex: 1,
    },
    cardTitle: {
      color: colors.text,
      fontSize: isTablet ? 20 : 22,
      lineHeight: isTablet ? 26 : 28,
      fontWeight: '800',
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    filterArea: {
      width: isTablet ? 'auto' : '100%',
      position: 'relative',
    },
    filterAreaOpen: {
      zIndex: 80,
    },
    filterRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
      alignItems: 'stretch',
    },
    filterSelectButton: {
      minWidth: isTablet ? 156 : '48%',
      minHeight: 56,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 10,
      justifyContent: 'space-between',
    },
    filterSelectButtonActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    filterSelectButtonDisabled: {
      opacity: 0.6,
    },
    filterSelectLabel: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.9,
      textTransform: 'uppercase',
    },
    filterSelectValueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    filterSelectValue: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    filterDropdownPanel: {
      position: 'absolute',
      top: 64,
      right: 0,
      left: isTablet ? undefined : 0,
      minWidth: isTablet ? 320 : undefined,
      maxWidth: isTablet ? 360 : undefined,
      gap: 14,
      padding: 16,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: 0.22,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 14,
      zIndex: 90,
    },
    filterDropdownHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    filterDropdownTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    filterDropdownClose: {
      minHeight: 30,
      borderRadius: 999,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterDropdownCloseText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    filterOptionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    filterOption: {
      minHeight: 38,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterOptionActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    filterOptionDisabled: {
      opacity: 0.6,
    },
    filterOptionText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    filterOptionTextActive: {
      color: colors.onPrimary,
    },
    activityInsightRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    activityInsightCard: {
      flex: 1,
      minWidth: isTablet ? 180 : 150,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 16,
      paddingVertical: 14,
      gap: 6,
    },
    activityInsightLabel: {
      color: colors.textSubtle,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.9,
      textTransform: 'uppercase',
    },
    activityInsightValue: {
      color: colors.text,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '800',
    },
    activityInsightMeta: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    chartBoard: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 12,
    },
    chartScaleColumn: {
      height: 236,
      justifyContent: 'space-between',
      paddingBottom: 24,
    },
    chartScaleLabel: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '700',
    },
    chartScroll: {
      flex: 1,
    },
    chartContent: {
      paddingRight: 6,
    },
    chartFrame: {
      minWidth: isTablet ? undefined : 720,
      height: 236,
      justifyContent: 'flex-end',
      position: 'relative',
    },
    chart: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: isTablet ? 3 : 2,
      height: 236,
      position: 'relative',
    },
    chartGridLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      height: 1,
      backgroundColor: colors.border,
      opacity: 0.7,
    },
    chartColumnWrap: {
      width: isTablet ? 32 : 28,
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 6,
      paddingVertical: 4,
      borderRadius: 16,
    },
    chartColumnWrapSelected: {
      backgroundColor: colors.surfaceMuted,
    },
    chartValue: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '800',
    },
    chartValueSelected: {
      color: colors.primary,
    },
    chartTrack: {
      width: isTablet ? 22 : 20,
      height: 184,
      borderRadius: 0,
      justifyContent: 'flex-end',
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    chartTrackSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    chartColumn: {
      width: '100%',
      minHeight: 8,
      borderRadius: 0,
      backgroundColor: colors.primary,
    },
    chartColumnEmpty: {
      backgroundColor: colors.surfaceStrong,
    },
    chartColumnHighlighted: {
      backgroundColor: colors.secondary,
    },
    chartColumnSelected: {
      backgroundColor: colors.primaryContainer,
    },
    chartLabel: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '700',
    },
    chartLabelSelected: {
      color: colors.primary,
    },
    activitySummaryHeader: {
      marginTop: -4,
    },
    activitySummaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    activitySummaryCard: {
      minWidth: isTablet ? 112 : 96,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 4,
    },
    activitySummaryCardSelected: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    activitySummaryDay: {
      color: colors.text,
      fontSize: 11,
      fontWeight: '800',
    },
    activitySummaryDaySelected: {
      color: colors.accentText,
    },
    activitySummaryValue: {
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
    },
    activitySummaryValueSelected: {
      color: colors.accentText,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: isTablet ? 40 : 18,
      paddingVertical: 20,
      backgroundColor: colors.overlay,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    modalCard: {
      alignSelf: 'center',
      width: '100%',
      maxWidth: isTablet ? 560 : 420,
      maxHeight: '80%',
      borderRadius: 28,
      padding: isTablet ? 20 : 18,
      backgroundColor: colors.surface,
      gap: 14,
    },
    modalHeader: {
      flexDirection: isTablet ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: isTablet ? 'flex-start' : 'stretch',
      gap: 10,
    },
    modalHeading: {
      flex: 1,
      gap: 4,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 20,
      lineHeight: 25,
      fontWeight: '800',
    },
    modalSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    modalCloseButton: {
      minHeight: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalCloseButtonText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    modalState: {
      minHeight: 100,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      gap: 10,
    },
    modalStateText: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'center',
      fontWeight: '600',
    },
    modalList: {
      flexGrow: 0,
    },
    modalListContent: {
      gap: 8,
      paddingBottom: 4,
    },
    respondentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    respondentIndexWrap: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    respondentIndex: {
      color: colors.onPrimary,
      fontSize: 12,
      fontWeight: '800',
    },
    respondentContent: {
      flex: 1,
      gap: 2,
    },
    respondentPrimary: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    respondentSecondary: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600',
    },
    tableCard: {
      gap: 0,
      padding: 0,
      overflow: 'hidden',
    },
    tableHeader: {
      paddingHorizontal: 24,
      paddingTop: 22,
      paddingBottom: 18,
      flexDirection: isTablet ? 'row' : 'column',
      justifyContent: 'space-between',
      alignItems: isTablet ? 'flex-start' : 'flex-start',
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    tableHeaderContent: {
      flex: 1,
      gap: 4,
    },
    resultsSummaryRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    resultsSummaryPill: {
      minWidth: isTablet ? 132 : 120,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 4,
    },
    resultsSummaryPillAccent: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    resultsSummaryLabel: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.9,
      textTransform: 'uppercase',
    },
    resultsSummaryValue: {
      color: colors.text,
      fontSize: 20,
      lineHeight: 24,
      fontWeight: '800',
    },
    resultsList: {
      gap: 12,
      paddingHorizontal: 20,
      paddingVertical: 20,
      backgroundColor: colors.surfaceMuted,
    },
    resultCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    resultCardExpanded: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
    },
    resultCardButton: {
      gap: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    resultHeaderMain: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    resultQuestionBadge: {
      minWidth: 48,
      minHeight: 30,
      borderRadius: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    resultQuestionBadgeText: {
      color: colors.onPrimary,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    resultQuestionContent: {
      flex: 1,
      gap: 8,
    },
    resultHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    resultMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    resultMetaPill: {
      minHeight: 28,
      borderRadius: 999,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    resultMetaPillMuted: {
      backgroundColor: colors.surfaceMuted,
    },
    resultMetaPillText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    resultMetaPillTextMuted: {
      color: colors.textMuted,
    },
    resultHelperText: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    resultToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingTop: 2,
    },
    resultToggleExpanded: {
      opacity: 1,
    },
    resultToggleText: {
      color: colors.textSubtle,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    resultToggleTextExpanded: {
      color: colors.primary,
    },
    resultToggleIconWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 1,
    },
    resultSummaryRowCompact: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    resultSummaryPillCompact: {
      flex: 1,
      minWidth: isTablet ? 180 : 150,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 3,
    },
    resultSummaryPillCompactAccent: {
      backgroundColor: colors.successBackground,
      borderColor: colors.successText,
    },
    resultSummaryPillLabel: {
      color: colors.textSubtle,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    resultSummaryPillLabelAccent: {
      color: colors.successText,
    },
    resultSummaryPillValue: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    resultSummaryPillValueAccent: {
      color: colors.successText,
    },
    tableQuestion: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '800',
    },
    tableMeta: {
      color: colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    resultExpandedWrap: {
      overflow: 'hidden',
    },
    resultExpandedSection: {
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surfaceMuted,
    },
    resultOptionsList: {
      gap: 8,
    },
    resultOptionCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
    },
    resultOptionCardTop: {
      backgroundColor: colors.successBackground,
      borderColor: colors.successText,
    },
    resultOptionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    resultOptionLabel: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
    },
    resultOptionLabelTop: {
      color: colors.successText,
    },
    resultOptionCountWrap: {
      alignItems: 'flex-end',
      gap: 2,
    },
    resultOptionCount: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '800',
    },
    resultOptionCountTop: {
      color: colors.successText,
    },
    resultOptionPercent: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
    },
    resultOptionPercentTop: {
      color: colors.successText,
    },
    resultOptionBarRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    resultOptionBarTrack: {
      flex: 1,
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.surfaceStrong,
      overflow: 'hidden',
    },
    resultOptionBarFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    resultOptionBarFillTop: {
      backgroundColor: colors.successText,
    },
    tableFooter: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 24,
      paddingVertical: 16,
      backgroundColor: colors.surfaceMuted,
    },
    tableFooterButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 42,
      borderRadius: 14,
      paddingHorizontal: 14,
      backgroundColor: colors.primarySoft,
    },
    tableFooterText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
  });
}
