import type { DashboardActivityPoint, SurveyQuestion } from '../types';

export const dailySurveyActivity: DashboardActivityPoint[] = [
  { label: '01', completions: 16 },
  { label: '02', completions: 18 },
  { label: '03', completions: 20 },
  { label: '04', completions: 17 },
  { label: '05', completions: 22 },
  { label: '06', completions: 24 },
  { label: '07', completions: 26 },
  { label: '08', completions: 23 },
  { label: '09', completions: 25 },
  { label: '10', completions: 29 },
  { label: '11', completions: 31 },
  { label: '12', completions: 34 },
  { label: '13', completions: 30 },
  { label: '14', completions: 33 },
  { label: '15', completions: 36 },
  { label: '16', completions: 35 },
  { label: '17', completions: 38 },
  { label: '18', completions: 37 },
  { label: '19', completions: 40 },
  { label: '20', completions: 42 },
  { label: '21', completions: 41 },
  { label: '22', completions: 38 },
  { label: '23', completions: 36 },
  { label: '24', completions: 34 },
  { label: '25', completions: 31 },
  { label: '26', completions: 29 },
  { label: '27', completions: 26 },
  { label: '28', completions: 24 },
  { label: '29', completions: 22 },
  { label: '30', completions: 19, highlighted: true },
];

export const initialSurveyQuestions: SurveyQuestion[] = [
  {
    id: 'Q-1042',
    title: 'How satisfied are you with today’s service experience?',
    helperText: 'Single response used for quick satisfaction tracking.',
    type: 'single',
    status: 'active',
    order: 1,
    updatedAt: 'Updated today',
    options: [
      { id: 'Q-1042-1', label: 'Very satisfied', responseCount: 126 },
      { id: 'Q-1042-2', label: 'Satisfied', responseCount: 84 },
      { id: 'Q-1042-3', label: 'Neutral', responseCount: 29 },
      { id: 'Q-1042-4', label: 'Dissatisfied', responseCount: 10 },
    ],
  },
  {
    id: 'Q-1043',
    title: 'Which service channel did you use during this visit?',
    helperText: 'Supports one answer per participant.',
    type: 'single',
    status: 'active',
    order: 2,
    updatedAt: 'Updated 2 hours ago',
    options: [
      { id: 'Q-1043-1', label: 'Front desk', responseCount: 73 },
      { id: 'Q-1043-2', label: 'Tablet kiosk', responseCount: 91 },
      { id: 'Q-1043-3', label: 'Call center', responseCount: 22 },
      { id: 'Q-1043-4', label: 'Mobile app', responseCount: 48 },
    ],
  },
  {
    id: 'Q-1044',
    title: 'Which features should be improved first?',
    helperText: 'Multiple choice question for prioritization.',
    type: 'multiple',
    status: 'active',
    order: 3,
    updatedAt: 'Updated yesterday',
    options: [
      { id: 'Q-1044-1', label: 'Queue time visibility', responseCount: 62 },
      { id: 'Q-1044-2', label: 'Staff guidance', responseCount: 47 },
      { id: 'Q-1044-3', label: 'Survey speed', responseCount: 34 },
      { id: 'Q-1044-4', label: 'Accessibility support', responseCount: 19 },
    ],
  },
  {
    id: 'Q-1045',
    title: 'Would you recommend this service to a friend or colleague?',
    helperText: 'Classic recommendation signal.',
    type: 'single',
    status: 'active',
    order: 4,
    updatedAt: 'Updated yesterday',
    options: [
      { id: 'Q-1045-1', label: 'Definitely', responseCount: 142 },
      { id: 'Q-1045-2', label: 'Maybe', responseCount: 36 },
      { id: 'Q-1045-3', label: 'Not likely', responseCount: 9 },
    ],
  },
  {
    id: 'Q-1046',
    title: 'What follow-up topics would you like to receive?',
    helperText: 'Draft question reserved for the next survey batch.',
    type: 'multiple',
    status: 'draft',
    order: 5,
    updatedAt: 'Drafted this week',
    options: [
      { id: 'Q-1046-1', label: 'Service tips', responseCount: 0 },
      { id: 'Q-1046-2', label: 'Promotions', responseCount: 0 },
      { id: 'Q-1046-3', label: 'Policy updates', responseCount: 0 },
    ],
  },
];
